### ISSUE TITLE
Chapter 6 "GalleryApp" PhotoImporter implementation class does not compile

### ISSUE THREAD

**Issue by shushu789** [PacktPublishing/MAUI-Projects-3rd-Edition#1]
**Hello, thanks for your book, I came across Chapter 6, GalleryApp, and when writing the code for the PhotoImporter implementation class it would not compile, I got the following 3 errors:** 

1. Partial method "PhotoImporter.Import()" must have an implementation part because it has accessibility modifier.

2. part of method 'PhotoImporter.Get(int, int, Quality)' must have an implementation part because it has accessibility modifier.

3. part of method 'PhotoImporter.Get(List<string>, Quality)' must have an implementation part because it has accessibility modifier.

### This is the 'IPhotoImporter' interface code：

```
public interface IPhotoImporter
{
    Task<ObservableCollection<Photo>> Get(int start, int count, Quality quality = Quality.Low); 
    Task<ObservableCollection<Photo>> Get(List<string> filenames, Quality quality = Quality.Low);
}
```

###  This is the code that implements class 'PhotoImporter ':

```

Internal part class PhotoImporter : IPhotoImporter
{
    private partial Task<string[]> Import();

    public partial Task<ObservableCollection<Photo>> Get(int start, int count, Quality quality);

    public partial Task<ObservableCollection<Photo>> Get(List<string> filenames, Quality quality);
}
```
![image](https://github.com/PacktPublishing/MAUI-Projects-3rd-Edition/assets/85976805/29e5c75d-1f4a-42d5-b141-6afafe1f5c6e)

In order to verify that I didn't write anything wrong, I even copied these two files of your source code into my project, but still the same error, I don't know what is wrong, I saw that your source code uses The version is .NET 7. I used .NET 7 and .NET 8 in my projects and both got the same error. However, it ran very well in your project. This problem caused me to struggle for a long time and I had to Came here like you looking for help, thank you

### my coding environment：

- Windows 10
- .NET 7/.NET 8
- visual studio 2022 17.9

**Comment by borrillis** [comment]
@shushu789 Thank you for reporting this, can you upload your project so that I can investigate? Additionally, are you trying to compile at the end of the chapter, or are you at some point in the middle?

**Comment by shushu789** [comment]
I compiled it in the middle, and I encountered an error when I finished writing the file "PhotoImporter.cs". Because it could not be compiled, I did not finish writing this project. I saw that it was just an implementation class and did not depend on the subsequent code. I am not sure. Is the understanding correct? Thank you for your reply

### This is the project address

[https://github.com/shushu789/GalleryApp.git](url)

**Comment by borrillis** [comment]
Hi @shushu789,
After looking at your project, it appears you are trying to compile before the "Requesting app permissions" section of Chapter 6. Your code looks accurate and, yes, it should not compile at this point. The `IPhotoImporter` and `PhotoImporter` classes are not complete implementations at this point. You will need to complete all of the platform implementations before the code will compile successfully. Please try to complete the next 2 sections before trying to compile again.
