### ISSUE TITLE
Chapter 2 - Misprints

### ISSUE THREAD

**Issue by khambley** [PacktPublishing/MAUI-Projects-3rd-Edition#2]
Great book so far! I've completed the first project, DoToo. Couple of things: (These may be related to me using .NET 8 vs. .NET 7 that you use in the book, but I thought I'd point them out regardless... The behavior, for me, was the same on all platforms, Win, iOS, and Android.
1. p.77 - ...Command="{Binding AddItemAsyncCommand}"... is not correct, it should be "AddItemCommand". It is correct in your code repo but the book is wrong.
2. p.78 ...Command="{Binding SaveAsyncCommand}"... is not correct, it should be "SaveCommand". It is correct in your code repo but the book is wrong.
3. p. 91 ...Command="{Binding ToggleFilterAsyncCommand}"... is not correct, it should be "ToggleFilterCommand". 
4. p. 92 <Setter Property="BackgroundColor"... did not work for me in .NET 8. I used <Setter Property="Background"... and the filter button worked as expected, changing background color dynamically based on value of ShowAll.

I downloaded and ran your code and it all worked as expected but again, I see you are targeting .NET 7 and I am targeting .NET 8.

**Comment by borrillis** [comment]
Hi @khambley Thanks for reporting these, I will take a look, items 1-3 should not depend on the version of .NET that you are using.

**Comment by borrillis** [comment]
@khambley , 
Again thanks for reporting these, I can confirm that 1.-3. are incorrect in the book, 4. Your change is correct for .NET 7 and .NET 8. The code in the repository is actually targeting .NET 6.
