### ISSUE TITLE
Ch2 Android

### ISSUE THREAD

**Issue by ext2txe** [PacktPublishing/MAUI-Projects-3rd-Edition#3]
Code built directly from repo source. Run on Android Emulator/default (Pixel 5) Create task and Save crashes the app.

Quick check on Windows  works correctly.

Great book so far!

**Comment by borrillis** [comment]
Hi @ext2txe, 
Thank you, and thanks for the report, I'll check that out.

**Comment by rajat-packt** [comment]
Hey @borrillis, if there are any updated instructions, please let me know, I'll add them to the repo's README

**Comment by borrillis** [comment]
@ext2txe
In the `ToDoItemRepository.cs` file, in the `CreateConnectionAsync` method, change the following line
```csharp
        var documentPath = Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments);
```
to
```csharp
        var documentPath = Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData);
```
