### ISSUE TITLE
news app does not have an api

### ISSUE THREAD

**Issue by TheRealKraytonian** [PacktPublishing/MAUI-Projects-3rd-Edition#4]
news app does not have an api

**Comment by mcumming** [comment]
Hi @TheRealKraytonian, I do not understand what the issue your having is fully. Can you provide more details on what the issue is specifically, either with the code in the repository, or the chapter in the book.

**Comment by marcomameli1992** [comment]
Dear, 
I try to create the app and it is compiled, but when it starts only the Loading view is visualized.
With the debug I have verified that it is possible to comunicate with the API and it works with also the decodification that are reported in the result object in the NewsService.cs 

How can I view the articles list in my app?
